version: "3.8"

services:
  medtechchain-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8088
    image: medtechchain/frontend
    container_name: medtechchain-frontend
    profiles:
      - dev
      - demo
    ports:
      - "3000:3000"
    networks:
      - medtechchain

networks:
  medtechchain:
    external: true
    name: medtechchain