version: "3.8"

# TODO: replace medtechchain with medtechchain
services:
  healthblocks-frontend:
    build:
      context: ./..
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8088
    image: medtechchain/frontend
    container_name: medtechchain-frontend
    profiles:
      - demo
    ports:
      - "3000:3000"
    networks:
      - medtechchain

networks:
  medtechchain:
    external: true
    name: medtechchain